### ISSUE TITLE
Unit-level event log of file uploads

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/national-paediatric-diabetes-audit#267]
Even if we don't keep old files, can we keep a log of upload dates. Maybe a unit-level event log?

We're getting units stating that they did upload some data before the Q1 deadline, but we can't confirm this as we only have the dates of the most recent upload. 

Does this make sense? Happy to discuss on Friday.

**Comment by mbarton** [comment]
Would update logs for people who enter directly on to the platform also be useful? It would be easy to add more per-unit logs once we build the infrastructure for it

**Comment by AmaniKrayemRCPCH** [comment]
It would be helpful! Thanks!

**Comment by eatyourpeas** [comment]
Just to say I have dones some work on this in PR #275. The Submission model tracks all CSV uploads for a given PDU and overwrites previous data if a new CSV is uploaded during the current audit period. See illustration:
<img width="2429" alt="image" src="https://github.com/user-attachments/assets/72687c24-0fc5-429e-87b3-02196c3ea805">
(currently RCPCH is treated like a PDU but obvs that will never happen)
Only for the currently active submission is the .csv stored - all previously uploaded csvs as well as associated patient data are deleted or overwritten. CSVs are retained for all active submissions in previous audit years (one for each PDU only).

In addition to this, an audit trail of user logs is retained - when people log in/out or reset their password, set up 2FA or fail to login. We also track if a person uploads a csv. See example here
![image](https://github.com/user-attachments/assets/6c527f00-80ee-4fa9-aff9-30ece1a1e96b)

I can also track if someone touches a patient record (ie updates or creates a patient or a visit) but this will make those logs possibly quite noisy for people who are using the platform questionnaire rather than the csv upload. Are we sure this is what we want?
