### ISSUE TITLE
add the data quality report to the csv as a separate sheet

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#370]
Having uploaded the csv, errors are now stored in the `Patient`, `Visit` and `Transfer` models.

They are now stored with the original csv row numbers in the `Submission` table too, to allow clinicians to cross-reference them with their own local version. They are rendered as a table on the Submission list view page in a data quality report.

It would be a useful feature to add this data quality report as a supplemental page attached to the uploaded data to download as a `.xlsx`. This would mean changing the `download_csv` to `download_xlsx` to allow a new page to be added, as well as maybe styling to the abnormal fields to highlight them

**Comment by mbarton** [comment]
I think we need a way to download the exact original CSV so that it can be used in any discussions between the audit team and users about what was uploaded when.

That doesn't necessarily mean we need to implement this as a separate download but lets not remove the ability to download the exact original CSV uploaded.

**Comment by reecehill** [comment]
My planned approach is to leave the new submission's .csv untouched.

1. Copy new_submission.csv_file to .xlsx
2. Style, format to show errors.
3. Append a new sheet to show errors in list format.
