### ISSUE TITLE
FIGMA Design: navbar and sitemap

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#390]
Hey @eatyourpeas  @AmaniKrayemRCPCH , sketched out couple versions of nav from what I can see on the local app so far. Happy to do each user's versions - what nav items should each role see?

![Image](https://github.com/user-attachments/assets/6b8bb1b2-818d-4113-8198-4da1dd543cc2)

https://www.figma.com/design/ejgejj2H1f7LNmHTpu2XDo/NPDA?node-id=43-162&t=4Ru8T6MEzPkK6cTK-1

**Comment by anchit-chandran** [comment]
#382 #374

**Comment by anchit-chandran** [comment]
@reecehill would you be able to add the control panel / PDU selector components? ![Image](https://github.com/user-attachments/assets/089adf4f-0728-416f-bb54-07605c2d8756)

**Comment by eatyourpeas** [comment]
My view is that if not logged in, only the User Guide should be viewable, and maybe a new home page that looks very similar to the current CSV upload page - basically the hero maybe with some tiles below with some signage advertise that this is a new platform brought to users by RCPCH, perhaps with some information for children and families.

On login, the user is redirected to the Dashboard, which has the graphs, some maps (perhaps only one), a snapshot of the clinic's 7 care processes, maybe some metrics that are important to clinicians, such as percentage of children with A1c < 58mmol/mol, percentage of children on pumps/closed loop and so on. Possibly a clinic break down by deprivation and sex and age.  I always think it is helpful to know which children are in transition, which are under 5, how many are primary age, and how many are in secondary school.

Once logged in, the nav bar has the options you already show. The questionnaire and upload csv links should possibly be combined into a drop down link with the name 'Submit Data'. On first submission, the session will update to reflect data submission method: those that upload a csv for the first time will nolonger be able to edit in the questionnaire - possibly the link to the questionnaire might be viewable still in the dropdown but be disabled, or could be left since users (after the latest PR) will be able to view data there, just not edit it. The submissions link should possibly be renamed to 'All Submissions' so a not to confuse people. The users link should be renamed to User Management or something a bit clearer.

Otherwise the structure as is I think is ok.

ideas here from @orangepeel73 @FrancescaAnnan very welcome

**Comment by anchit-chandran** [comment]
![Image](https://github.com/user-attachments/assets/9861c9cc-2799-48ba-b32d-5649f5ee3848)
Let me know thoughts

**Comment by AmaniKrayemRCPCH** [comment]
Looks great! Really like it with the dropdown

**Comment by FrancescaAnnan** [comment]
Sorry I was at EXTOD and had no time to look at anything.



Francesca

Francesca Annan

Lead Dietitian CYP Diabetes Service

Clinical Specialist Paediatric and Adolescent Diabetes Dietitian
Working days Monday -Friday 9am – 5pm
Children and Young People’s Diabetes Service, UCLH

Contact the Children’s Diabetes Dietitians on ***@***.******@***.***> | Diabetes information and advice can be found on our website www.uclh.nhs.uk/t1

We are committed to delivering top-quality patient care, excellent
education and world class research

safety  kindness  teamwork  improving

UCLH website<http://www.uclh.nhs.uk/> | Media<http://www.uclh.nhs.uk/aboutus/Media> | Become a member<http://www.uclh.nhs.uk/aboutus/FT/Pages/Becomeamember.aspx> | Support our charities<http://www.uclh.nhs.uk/aboutus/Campaignsandcharities> | Contact UCLH<http://www.uclh.nhs.uk/aboutus/Pages/ContactUs.aspx>
Find us on Facebook<http://www.facebook.com/UCLHNHS> | Follow us on Twitter<http://twitter.com/uclh> | Subscribe on YouTube<http://www.youtube.com/uclhvideo>





________________________________
